web_drive_executable_path='C:/Users/chyta/AppData/Local/Programs/Python/Python36/chromedriver.exe'
playing_squad_url='https://www.cricbuzz.com/cricket-match-facts/20250/ind-vs-aus-match-14-icc-cricket-world-cup-2019'
player_name_url='http://www.howstat.com/cricket/Statistics/Players/PlayerList.asp?Country=ALL&Group='
player_stats_url='http://howstat.com/cricket/Statistics/Players/PlayerProgressBat_ODI.asp?PlayerID='
stats_path='E:/cricbuzz/players/'